### ISSUE TITLE
Problem while respawning.

### ISSUE THREAD

**Issue by pingiun** [lukleh/TwistedBot#1]
When the bot is killed on the server, it crashes while trying to respawn. This is the error:
'Bot' object has no attribute 'send_packet'

The problem is that in the file botentity.py, there is no function called send_packet in that class.

Complete log:
19:27:33.317127 [BOT_ENTITY] Chat: twistedbot was slain by jell_e105
19:27:33.345123 [BOT_ENTITY] current health -5 food 20 saturation 5.0
19:27:34.348532 [-] Unhandled Error
    Traceback (most recent call last):
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/base.py", line 1178, in mainLoop
        self.runUntilCurrent()
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/base.py", line 800, in runUntilCurrent
        call.func(_call.args, *_call.kw)
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/defer.py", line 368, in callback
        self._startRunCallbacks(result)
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/defer.py", line 464, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/defer.py", line 551, in _runCallbacks
        current.result = callback(current.result, _args, *_kw)
      File "/home/jm/Documenten/TwistedBot-master/twistedbot/tools.py", line 27, in <lambda>
        d.addCallback(lambda ignored: fn(_args, *_kwargs))
      File "/home/jm/Documenten/TwistedBot-master/twistedbot/botentity.py", line 448, in do_respawn
        self.send_packet("client statuses", {"status": 1})
    exceptions.AttributeError: 'Bot' object has no attribute 'send_packet'

19:27:34.406262 [-] Unhandled error in Deferred:
19:27:34.406359 [-] Unhandled Error
    Traceback (most recent call last):
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/base.py", line 1178, in mainLoop
        self.runUntilCurrent()
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/base.py", line 800, in runUntilCurrent
        call.func(_call.args, *_call.kw)
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/defer.py", line 368, in callback
        self._startRunCallbacks(result)
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/defer.py", line 464, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/home/jm/Documenten/TwistedBot-master/libs/twisted/internet/defer.py", line 551, in _runCallbacks
        current.result = callback(current.result, _args, *_kw)
      File "/home/jm/Documenten/TwistedBot-master/twistedbot/logbot.py", line 13, in exit_on_error
        sys.exit(1)
    exceptions.SystemExit: 1

19:27:34.437509 [PROTOCOL] Connection lost, reason: Connection to the other side was lost in a non-clean fashion: Connection lost.

**Comment by lukleh** [comment]
fixed as part of [56e732f2](https://github.com/lukleh/TwistedBot/commit/56e732f2)
