### ISSUE TITLE
Some blocks wrongfully have inventory_avoid

### ISSUE THREAD

**Issue by vgel** [lukleh/TwistedBot#11]
Grass, Mycelium, active redstone lamps, the various ores, etc. can be picked up with silk touch or gotten in creative, so shouldn't be inventory_avoid. This is an issue because items.py line 1204 crashes trying to get the names of inventory_avoid items if they are picked up.

My feeling on how this should be fixed is inventory_avoid items should always be registered, since you can get them anyways (you don't want ops able to crash your bot out with /give on accident, or purpose), and may want them.

Full traceback:

```
18:42:52.688696 [-] Unhandled Error
    Traceback (most recent call last):
      File "/home/jon/Dropbox/prog/TwistedBot/libs/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/home/jon/Dropbox/prog/TwistedBot/libs/twisted/internet/selectreactor.py", line 151, in _doReadOrWrite
        why = getattr(selectable, method)()
      File "/home/jon/Dropbox/prog/TwistedBot/libs/twisted/internet/tcp.py", line 215, in doRead
        return self._dataReceived(data)
      File "/home/jon/Dropbox/prog/TwistedBot/libs/twisted/internet/tcp.py", line 221, in _dataReceived
        rval = self.protocol.dataReceived(data)
    --- <exception caught here> ---
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/factory.py", line 125, in dataReceived
        self.parse_stream(bytestream)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/factory.py", line 136, in parse_stream
        self.packet_iter(self.packets)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/factory.py", line 147, in packet_iter
        self.process_packet(packet)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/factory.py", line 155, in process_packet
        f(payload)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/factory.py", line 214, in p_collect
        self.event.on_collect.fire(collected_eid=c.collected_eid, collector_eid=c.collector_eid)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/eventregister.py", line 20, in fire
        handler(*args, **kwargs)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/plugins/core/protocol_events.py", line 92, in on_collect
        self.world.inventories.collect_action(collected_eid=collected_eid, collector_eid=collector_eid)
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/inventory.py", line 222, in collect_action
        self.item_collected_count[itemstack.name] += itemstack.count
      File "/home/jon/Dropbox/prog/TwistedBot/twistedbot/items.py", line 1204, in name
        return self.item.name if self.common else self.item.get_name(self.meta)
    exceptions.AttributeError: 'NoneType' object has no attribute 'get_name'
```

**Comment by lukleh** [comment]
That is true. For now I ignore enchantments as that would complicate things at this moment. I have more important problems to solve in bot (behavior, grid pathfinding).
This is pretty much the first draft (items), very probably it will be rewritten when situation arises.

**Comment by vgel** [comment]
Ok, seems reasonable. In the meantime, I pushed a temporary fix to my fork, if you want I can send it as a pull request.

**Comment by lukleh** [comment]
Sure, I can't promise I will use it but I would like to look at your changes.

Sidenote: the behavior_tree.py will be very probably heavily rewritten, or swapped for something better. So I can't guarantee that you trying to fix stuff there is not going to be a waste of time.

**Comment by vgel** [comment]
That's fine, I'm mainly just going around fixing crashes I find.

I'll push my block fixes right after I fix this grass problem.

**Comment by lukleh** [comment]
Cool, targeted pull requests for bugs&crashes are great help.
