### ISSUE TITLE
Outdated client!

### ISSUE THREAD

**Issue by nelix** [lukleh/TwistedBot#14]
How would I go about adding support for new minecraft snapshots?

**Comment by lukleh** [comment]
update the packets.py according to http://wiki.vg/Pre-release_protocol
then update any related code

**Comment by nelix** [comment]
I have pumped the protocol version to 71, it now connects but halts on this stack trace:
22:29:20.123819 [CORE EVENT] Spawn position: 92 64 256
22:29:21.074693 [-] Unhandled Error
        Traceback (most recent call last):
          File "/Users/nathanhutchison/TwistedBot/libs/twisted/python/context.py", line 81, in callWithContext
            return func(_args,_*kw)
          File "/Users/nathanhutchison/TwistedBot/libs/twisted/internet/selectreactor.py", line 151, in _doReadOrWrite
            why = getattr(selectable, method)()
          File "/Users/nathanhutchison/TwistedBot/libs/twisted/internet/tcp.py", line 215, in doRead
            return self._dataReceived(data)
          File "/Users/nathanhutchison/TwistedBot/libs/twisted/internet/tcp.py", line 221, in _dataReceived
            rval = self.protocol.dataReceived(data)
        --- <exception caught here> ---
          File "/Users/nathanhutchison/TwistedBot/twistedbot/factory.py", line 125, in dataReceived
            self.parse_stream(bytestream)
          File "/Users/nathanhutchison/TwistedBot/twistedbot/factory.py", line 132, in parse_stream
            parsed_packets, self.leftover = parse_packets(self.leftover + bytestream)
          File "/Users/nathanhutchison/TwistedBot/twistedbot/packets.py", line 759, in parse_packets
            container = packet_stream.parse(bytestream)
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 188, in parse
            return self.parse_stream(BytesIO(data))
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 198, in parse_stream
            return self._parse(stream, Container())
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 670, in _parse
            subobj = sc._parse(stream, context)
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 527, in _parse
            obj.append(self.subcon._parse(stream, context))
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 670, in _parse
            subobj = sc._parse(stream, context)
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 851, in _parse
            obj = self.cases.get(key, self.default)._parse(stream, context)
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 670, in _parse
            subobj = sc._parse(stream, context)
          File "/Users/nathanhutchison/TwistedBot/libs/construct/core.py", line 288, in _parse
            return self._decode(self.subcon._parse(stream, context), context)
          File "/Users/nathanhutchison/TwistedBot/libs/construct/adapters.py", line 158, in _decode
            obj.decode(self.encoding)
        exceptions.UnicodeDecodeError: 'utf16' codec can't decode bytes in position 274-275: illegal UTF-16 surrogate

**Comment by lukleh** [comment]
you mean, you updated the corresponding packets and then changed the version number to 71?

**Comment by nelix** [comment]
At that stage I had not, I now realise why the utf16 error happens, the length of certain packets changed. Now I have it connecting (A buddy gave me a hand). Still more stuff todo.
Sorry for troubling you, this is not really an issue at all is it?

**Comment by lukleh** [comment]
I stopped following snapshot releases. I stick with the stable versions.

**Comment by nelix** [comment]
Fair enough, would break things for people with stable servers anyway.
